### ISSUE TITLE
ValueError: Cannot create group in read only mode.加载模型就错了，很奇怪

### ISSUE THREAD

**Issue by ThinkPeace** [Devinxiao/h5_to_weight_yolo3#1]
Using TensorFlow backend.
Traceback (most recent call last):
  File "d:/project/keras-yolo3-master/h5_to_weight_yolo3-master/check_weight.py", line 11, in <module>
    model = load_model('trained_weights_final.h5',compile=False)
  File "D:\anaconda\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "D:\anaconda\lib\site-packages\keras\engine\saving.py", line 221, in _deserialize_model
    model_config = f['model_config']
  File "D:\anaconda\lib\site-packages\keras\utils\io_utils.py", line 302, in __getitem__
    raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.

**Comment by caimingxie** [comment]
It cause by 'trained_weights_final.h5'  when save h5 file not include model just  weights,  it was solved now.

**Comment by zhangyufei1995** [comment]
@ThinkPeace  do you solve it?

**Comment by zhangyufei1995** [comment]
@caimingxie  hello ，i use the 'model.save_weights' to save a ".h5" file ,can i use your code convert it to .weights file?

**Comment by caimingxie** [comment]
@zhangyufei1995  yes, it will be ok. if have any other problem please tell me .

**Comment by zhangyufei1995** [comment]
@caimingxie  thanks very much ,it works now. i have another issue,can your code convert yolov3_tiny's mode(.h5) to  .weights file?

**Comment by caimingxie** [comment]
this issue has salved.
